### ISSUE TITLE
HA error - v 2023.03.05 / esphome.dev

### ISSUE THREAD

**Issue by ronaldt80** [jagheterfredrik/wallbox-ble#2]
Hi, noticed the HA .5 update supports your new pairing method for the ble pairing, so once upgraded enabled my Bluetooth proxy based on esphome Dev. My HA log shows below error, any idea what this is related to? Do I need to update something in yaml?

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 23:29:52 (1 occurrences)
Last logged: 23:29:52

Detected integration that attempted to call BleakClient with an address instead of a BLEDevice. Please report issue to the custom integration author for wallbox_ble using this method at custom_components/wallbox_ble/api.py, line 136: async with BleakClient(device, disconnected_callback=disconnected_callback) as self.client:
```

**Comment by jagheterfredrik** [comment]
I don’t think it landed in 2023.3.5, only the bumped aioesphomeapi. The pairing is in dev now so I assume it’ll be in next release.

see https://github.com/home-assistant/core/blob/2023.3.5/homeassistant/components/esphome/bluetooth/client.py#L388

**Comment by jagheterfredrik** [comment]
Regarding the warning, I think it’s being called with None rather than an address. It’s slightly misleading and even if it should be fixed shouldn’t cause any issues.

**Comment by jagheterfredrik** [comment]
Made a workaround, try it out!

**Comment by ronaldt80** [comment]
No more error :)

Still no connection with the Wallbox though. Guess I have to be a bit more patient!
