### ISSUE TITLE
BLE Proxy ESPHome help

### ISSUE THREAD

**Issue by cliffdude** [jagheterfredrik/wallbox-ble#3]
I want to try and move my WB pulsar plus to Bluetooth as the Wifi / cloud is unreliable on a good day!
My HA is far away from the WB so direct Bluetooth is not an option (I don't think it even has BT hardware) thus I would like to clarify if I have understood correctly what is requiered to get this up and running.
What I understand from reading the forum is that I need an ESP32 module flashed with ESPHome BLE_Proxy, not sure if there are any specific settings in the yaml?
Install this repo to HA via HACS and all should work. BUT...
How do I pair the WB to HA and am I missing anything? 
Does it auto detect the WB somehow?

Sorry to be a PITA.

**Comment by jagheterfredrik** [comment]
You got it right. The WB will be auto detected 👍

**Comment by cliffdude** [comment]
Awsome, it's working! Thanks for your work on this.
For anyone that may read this in the future, I have used a Sonoff DualR3 (ESP32) that controls some lights in my hallway near the wallbox and just added the following lines to the YAML and flashed. 
This will not work on older versions of HA or ESPHome.

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
